language: python
python:
  - "3.7"
before_install:
  # command to update pip
  - python -m pip install --upgrade pip
  # command to copy settings
  - cp settings.py.example settings.py
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests.py
